# coding: utf-8

"""
    The SMS Works API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.batch_messages_api import BatchMessagesApi


class TestBatchMessagesApi(unittest.TestCase):
    """ BatchMessagesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.batch_messages_api.BatchMessagesApi()

    def tearDown(self):
        pass

    def test_cancel_scheduled_batch_job(self):
        """
        Test case for cancel_scheduled_batch_job

        
        """
        pass

    def test_get_batch_by_id(self):
        """
        Test case for get_batch_by_id

        
        """
        pass

    def test_schedule_batch(self):
        """
        Test case for schedule_batch

        
        """
        pass

    def test_send_batch(self):
        """
        Test case for send_batch

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
