# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

    The version of the OpenAPI document: 1.9.0
    Contact: support@thesmsworks.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.scheduled_messages_response import ScheduledMessagesResponse

class TestScheduledMessagesResponse(unittest.TestCase):
    """ScheduledMessagesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduledMessagesResponse:
        """Test ScheduledMessagesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduledMessagesResponse`
        """
        model = ScheduledMessagesResponse()
        if include_optional:
            return ScheduledMessagesResponse(
                status = 'PROCESSED',
                id = '1910600',
                batch = True,
                message = {"sender":"MyCompany","destination":"07777777777","content":"Greetings on schedule!","schedule":"2021-10-28T13:10:00.000Z"}
            )
        else:
            return ScheduledMessagesResponse(
        )
        """

    def testScheduledMessagesResponse(self):
        """Test ScheduledMessagesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
