# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.credits_api import CreditsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCreditsApi(unittest.TestCase):
    """CreditsApi unit test stubs"""

    def setUp(self):
        self.api = api.credits_api.CreditsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_credits(self):
        """Test case for credits

        """
        pass


if __name__ == '__main__':
    unittest.main()
