# coding: utf-8

"""
    The SMS Works API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.utils_api import UtilsApi


class TestUtilsApi(unittest.TestCase):
    """ UtilsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.utils_api.UtilsApi()

    def tearDown(self):
        pass

    def test_hello(self):
        """
        Test case for hello

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
