# coding: utf-8

"""
    The SMS Works API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.query import Query


class TestQuery(unittest.TestCase):
    """ Query unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuery(self):
        """
        Test Query
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.query.Query()
        pass


if __name__ == '__main__':
    unittest.main()
