# coding: utf-8

"""
    The SMS Works API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.scheduled_batch_response import ScheduledBatchResponse


class TestScheduledBatchResponse(unittest.TestCase):
    """ ScheduledBatchResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduledBatchResponse(self):
        """
        Test ScheduledBatchResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.scheduled_batch_response.ScheduledBatchResponse()
        pass


if __name__ == '__main__':
    unittest.main()
