# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

    The version of the OpenAPI document: 1.9.0
    Contact: support@thesmsworks.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.one_time_password_api import OneTimePasswordApi


class TestOneTimePasswordApi(unittest.TestCase):
    """OneTimePasswordApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OneTimePasswordApi()

    def tearDown(self) -> None:
        pass

    def test_otp_messageid_get(self) -> None:
        """Test case for otp_messageid_get

        """
        pass

    def test_otp_send_post(self) -> None:
        """Test case for otp_send_post

        """
        pass

    def test_otp_verify_post(self) -> None:
        """Test case for otp_verify_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
