# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

    The version of the OpenAPI document: 1.9.0
    Contact: support@thesmsworks.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.otp_verify_response import OTPVerifyResponse

class TestOTPVerifyResponse(unittest.TestCase):
    """OTPVerifyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OTPVerifyResponse:
        """Test OTPVerifyResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OTPVerifyResponse`
        """
        model = OTPVerifyResponse()
        if include_optional:
            return OTPVerifyResponse(
                destination = '447777000000',
                status = 'VERIFIED',
                passcode = 123456,
                validity = 300,
                metadata = {"customer_id":"ABC123","cart_id":"XYZ789"},
                created = 'Tue Apr 25 2023 16:47:00 GMT+0100 (British Summer Time)',
                expires = 'Tue Apr 25 2023 16:57:00 GMT+0100 (British Summer Time)',
                modified = 'Tue Apr 25 2023 16:49:20 GMT+0100 (British Summer Time)'
            )
        else:
            return OTPVerifyResponse(
        )
        """

    def testOTPVerifyResponse(self):
        """Test OTPVerifyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
