# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.utils_api import UtilsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUtilsApi(unittest.TestCase):
    """UtilsApi unit test stubs"""

    def setUp(self):
        self.api = api.utils_api.UtilsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_error(self):
        """Test case for get_error

        """
        pass

    def test_test(self):
        """Test case for test

        """
        pass


if __name__ == '__main__':
    unittest.main()
