# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.auth_api import AuthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_key_secret(self):
        """Test case for key_secret

        """
        pass

    def test_login(self):
        """Test case for login

        """
        pass


if __name__ == '__main__':
    unittest.main()
