# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

    The version of the OpenAPI document: 1.9.0
    Contact: support@thesmsworks.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.otp_response import OTPResponse

class TestOTPResponse(unittest.TestCase):
    """OTPResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OTPResponse:
        """Test OTPResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OTPResponse`
        """
        model = OTPResponse()
        if include_optional:
            return OTPResponse(
                messageid = '52692416-ce9e-45ad-aa1e-14fcee8fa662',
                status = 'SENT',
                credits = 561,
                credits_used = 1,
                messageparts = 1
            )
        else:
            return OTPResponse(
        )
        """

    def testOTPResponse(self):
        """Test OTPResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
