# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

    The version of the OpenAPI document: 1.9.0
    Contact: support@thesmsworks.co.uk
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.otp import OTP

class TestOTP(unittest.TestCase):
    """OTP unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OTP:
        """Test OTP
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OTP`
        """
        model = OTP()
        if include_optional:
            return OTP(
                sender = 'YourCompany',
                destination = '7777777777',
                length = None,
                template = 'This is your one-time passcode - {{passcode}}',
                validity = 300,
                passcode = '123456',
                metadata = {"customer_id":"ABC123","cart_id":"XYZ789"}
            )
        else:
            return OTP(
        )
        """

    def testOTP(self):
        """Test OTP"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
