# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.messages_api import MessagesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = api.messages_api.MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_scheduled_job(self):
        """Test case for cancel_scheduled_job

        """
        pass

    def test_get_failed_messages(self):
        """Test case for get_failed_messages

        """
        pass

    def test_get_inbox_messages(self):
        """Test case for get_inbox_messages

        """
        pass

    def test_get_message_by_id(self):
        """Test case for get_message_by_id

        """
        pass

    def test_get_messages(self):
        """Test case for get_messages

        """
        pass

    def test_schedule_message(self):
        """Test case for schedule_message

        """
        pass

    def test_send_flash_message(self):
        """Test case for send_flash_message

        """
        pass

    def test_send_message(self):
        """Test case for send_message

        """
        pass


if __name__ == '__main__':
    unittest.main()
