# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.scheduled_batch_response import ScheduledBatchResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestScheduledBatchResponse(unittest.TestCase):
    """ScheduledBatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduledBatchResponse(self):
        """Test ScheduledBatchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scheduled_batch_response.ScheduledBatchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
