# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.3.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.error_model import ErrorModel 


class ExtendedErrorModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'error_code': 'float',
        'status': 'str',
        'permanent': 'bool'
    }
    if hasattr(ErrorModel, "swagger_types"):
        swagger_types.update(ErrorModel.swagger_types)

    attribute_map = {
        'message': 'message',
        'error_code': 'errorCode',
        'status': 'status',
        'permanent': 'permanent'
    }
    if hasattr(ErrorModel, "attribute_map"):
        attribute_map.update(ErrorModel.attribute_map)

    def __init__(self, message=None, error_code=None, status=None, permanent=None, *args, **kwargs):  # noqa: E501
        """ExtendedErrorModel - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self._error_code = None
        self._status = None
        self._permanent = None
        self.discriminator = None
        self.message = message
        self.error_code = error_code
        self.status = status
        if permanent is not None:
            self.permanent = permanent
        ErrorModel.__init__(self, *args, **kwargs)

    @property
    def message(self):
        """Gets the message of this ExtendedErrorModel.  # noqa: E501


        :return: The message of this ExtendedErrorModel.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ExtendedErrorModel.


        :param message: The message of this ExtendedErrorModel.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def error_code(self):
        """Gets the error_code of this ExtendedErrorModel.  # noqa: E501

        Numeric code used to identify the error. Integer.  # noqa: E501

        :return: The error_code of this ExtendedErrorModel.  # noqa: E501
        :rtype: float
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this ExtendedErrorModel.

        Numeric code used to identify the error. Integer.  # noqa: E501

        :param error_code: The error_code of this ExtendedErrorModel.  # noqa: E501
        :type: float
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def status(self):
        """Gets the status of this ExtendedErrorModel.  # noqa: E501


        :return: The status of this ExtendedErrorModel.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ExtendedErrorModel.


        :param status: The status of this ExtendedErrorModel.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def permanent(self):
        """Gets the permanent of this ExtendedErrorModel.  # noqa: E501


        :return: The permanent of this ExtendedErrorModel.  # noqa: E501
        :rtype: bool
        """
        return self._permanent

    @permanent.setter
    def permanent(self, permanent):
        """Sets the permanent of this ExtendedErrorModel.


        :param permanent: The permanent of this ExtendedErrorModel.  # noqa: E501
        :type: bool
        """

        self._permanent = permanent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExtendedErrorModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExtendedErrorModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
