# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.big_decimal import BigDecimal  # noqa: F401,E501


class MessageResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'batchid': 'str',
        'content': 'str',
        'created': 'str',
        'customerid': 'str',
        'destination': 'BigDecimal',
        'failurereason': 'object',
        'id': 'str',
        'keyword': 'str',
        'messageid': 'str',
        'modified': 'str',
        'schedule': 'str',
        'status': 'str',
        'sender': 'str',
        'tag': 'str'
    }

    attribute_map = {
        'batchid': 'batchid',
        'content': 'content',
        'created': 'created',
        'customerid': 'customerid',
        'destination': 'destination',
        'failurereason': 'failurereason',
        'id': 'id',
        'keyword': 'keyword',
        'messageid': 'messageid',
        'modified': 'modified',
        'schedule': 'schedule',
        'status': 'status',
        'sender': 'sender',
        'tag': 'tag'
    }

    def __init__(self, batchid=None, content=None, created=None, customerid=None, destination=None, failurereason=None, id=None, keyword=None, messageid=None, modified=None, schedule=None, status=None, sender=None, tag=None):  # noqa: E501
        """MessageResponse - a model defined in Swagger"""  # noqa: E501
        self._batchid = None
        self._content = None
        self._created = None
        self._customerid = None
        self._destination = None
        self._failurereason = None
        self._id = None
        self._keyword = None
        self._messageid = None
        self._modified = None
        self._schedule = None
        self._status = None
        self._sender = None
        self._tag = None
        self.discriminator = None
        self.batchid = batchid
        self.content = content
        self.created = created
        self.customerid = customerid
        self.destination = destination
        if failurereason is not None:
            self.failurereason = failurereason
        if id is not None:
            self.id = id
        self.keyword = keyword
        self.messageid = messageid
        self.modified = modified
        self.schedule = schedule
        self.status = status
        self.sender = sender
        self.tag = tag

    @property
    def batchid(self):
        """Gets the batchid of this MessageResponse.  # noqa: E501


        :return: The batchid of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._batchid

    @batchid.setter
    def batchid(self, batchid):
        """Sets the batchid of this MessageResponse.


        :param batchid: The batchid of this MessageResponse.  # noqa: E501
        :type: str
        """
        if batchid is None:
            raise ValueError("Invalid value for `batchid`, must not be `None`")  # noqa: E501

        self._batchid = batchid

    @property
    def content(self):
        """Gets the content of this MessageResponse.  # noqa: E501


        :return: The content of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this MessageResponse.


        :param content: The content of this MessageResponse.  # noqa: E501
        :type: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def created(self):
        """Gets the created of this MessageResponse.  # noqa: E501


        :return: The created of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this MessageResponse.


        :param created: The created of this MessageResponse.  # noqa: E501
        :type: str
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")  # noqa: E501

        self._created = created

    @property
    def customerid(self):
        """Gets the customerid of this MessageResponse.  # noqa: E501


        :return: The customerid of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._customerid

    @customerid.setter
    def customerid(self, customerid):
        """Sets the customerid of this MessageResponse.


        :param customerid: The customerid of this MessageResponse.  # noqa: E501
        :type: str
        """
        if customerid is None:
            raise ValueError("Invalid value for `customerid`, must not be `None`")  # noqa: E501

        self._customerid = customerid

    @property
    def destination(self):
        """Gets the destination of this MessageResponse.  # noqa: E501


        :return: The destination of this MessageResponse.  # noqa: E501
        :rtype: BigDecimal
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this MessageResponse.


        :param destination: The destination of this MessageResponse.  # noqa: E501
        :type: BigDecimal
        """
        if destination is None:
            raise ValueError("Invalid value for `destination`, must not be `None`")  # noqa: E501

        self._destination = destination

    @property
    def failurereason(self):
        """Gets the failurereason of this MessageResponse.  # noqa: E501


        :return: The failurereason of this MessageResponse.  # noqa: E501
        :rtype: object
        """
        return self._failurereason

    @failurereason.setter
    def failurereason(self, failurereason):
        """Sets the failurereason of this MessageResponse.


        :param failurereason: The failurereason of this MessageResponse.  # noqa: E501
        :type: object
        """

        self._failurereason = failurereason

    @property
    def id(self):
        """Gets the id of this MessageResponse.  # noqa: E501


        :return: The id of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MessageResponse.


        :param id: The id of this MessageResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def keyword(self):
        """Gets the keyword of this MessageResponse.  # noqa: E501


        :return: The keyword of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this MessageResponse.


        :param keyword: The keyword of this MessageResponse.  # noqa: E501
        :type: str
        """
        if keyword is None:
            raise ValueError("Invalid value for `keyword`, must not be `None`")  # noqa: E501

        self._keyword = keyword

    @property
    def messageid(self):
        """Gets the messageid of this MessageResponse.  # noqa: E501


        :return: The messageid of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._messageid

    @messageid.setter
    def messageid(self, messageid):
        """Sets the messageid of this MessageResponse.


        :param messageid: The messageid of this MessageResponse.  # noqa: E501
        :type: str
        """
        if messageid is None:
            raise ValueError("Invalid value for `messageid`, must not be `None`")  # noqa: E501

        self._messageid = messageid

    @property
    def modified(self):
        """Gets the modified of this MessageResponse.  # noqa: E501


        :return: The modified of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this MessageResponse.


        :param modified: The modified of this MessageResponse.  # noqa: E501
        :type: str
        """
        if modified is None:
            raise ValueError("Invalid value for `modified`, must not be `None`")  # noqa: E501

        self._modified = modified

    @property
    def schedule(self):
        """Gets the schedule of this MessageResponse.  # noqa: E501


        :return: The schedule of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this MessageResponse.


        :param schedule: The schedule of this MessageResponse.  # noqa: E501
        :type: str
        """
        if schedule is None:
            raise ValueError("Invalid value for `schedule`, must not be `None`")  # noqa: E501

        self._schedule = schedule

    @property
    def status(self):
        """Gets the status of this MessageResponse.  # noqa: E501


        :return: The status of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MessageResponse.


        :param status: The status of this MessageResponse.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def sender(self):
        """Gets the sender of this MessageResponse.  # noqa: E501


        :return: The sender of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this MessageResponse.


        :param sender: The sender of this MessageResponse.  # noqa: E501
        :type: str
        """
        if sender is None:
            raise ValueError("Invalid value for `sender`, must not be `None`")  # noqa: E501

        self._sender = sender

    @property
    def tag(self):
        """Gets the tag of this MessageResponse.  # noqa: E501


        :return: The tag of this MessageResponse.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this MessageResponse.


        :param tag: The tag of this MessageResponse.  # noqa: E501
        :type: str
        """
        if tag is None:
            raise ValueError("Invalid value for `tag`, must not be `None`")  # noqa: E501

        self._tag = tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessageResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessageResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
