# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.  # noqa: E501

    OpenAPI spec version: 1.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Query(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'destination': 'str',
        'sender': 'str',
        'keyword': 'str',
        '_from': 'str',
        'to': 'str',
        'metadata': 'object'
    }

    attribute_map = {
        'status': 'status',
        'destination': 'destination',
        'sender': 'sender',
        'keyword': 'keyword',
        '_from': 'from',
        'to': 'to',
        'metadata': 'metadata'
    }

    def __init__(self, status=None, destination=None, sender=None, keyword=None, _from=None, to=None, metadata=None):  # noqa: E501
        """Query - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._destination = None
        self._sender = None
        self._keyword = None
        self.__from = None
        self._to = None
        self._metadata = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if destination is not None:
            self.destination = destination
        if sender is not None:
            self.sender = sender
        if keyword is not None:
            self.keyword = keyword
        if _from is not None:
            self._from = _from
        if to is not None:
            self.to = to
        if metadata is not None:
            self.metadata = metadata

    @property
    def status(self):
        """Gets the status of this Query.  # noqa: E501

        The status of the messages you would like returned (either 'SENT', 'DELIVERED', 'EXPIRED', 'DELETED', 'UNDELIVERABLE', 'ACCEPTED', 'UNKNOWN', 'REJECTED')  # noqa: E501

        :return: The status of this Query.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Query.

        The status of the messages you would like returned (either 'SENT', 'DELIVERED', 'EXPIRED', 'DELETED', 'UNDELIVERABLE', 'ACCEPTED', 'UNKNOWN', 'REJECTED')  # noqa: E501

        :param status: The status of this Query.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def destination(self):
        """Gets the destination of this Query.  # noqa: E501

        The phone number of the recipient. Start UK numbers with 44 and drop the leading 0.  # noqa: E501

        :return: The destination of this Query.  # noqa: E501
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this Query.

        The phone number of the recipient. Start UK numbers with 44 and drop the leading 0.  # noqa: E501

        :param destination: The destination of this Query.  # noqa: E501
        :type: str
        """

        self._destination = destination

    @property
    def sender(self):
        """Gets the sender of this Query.  # noqa: E501

        The sender of the message (this can be the configured sender name for an outbound message or the senders phone number for an inbound message).  # noqa: E501

        :return: The sender of this Query.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this Query.

        The sender of the message (this can be the configured sender name for an outbound message or the senders phone number for an inbound message).  # noqa: E501

        :param sender: The sender of this Query.  # noqa: E501
        :type: str
        """

        self._sender = sender

    @property
    def keyword(self):
        """Gets the keyword of this Query.  # noqa: E501

        The keyword used in the inbound message  # noqa: E501

        :return: The keyword of this Query.  # noqa: E501
        :rtype: str
        """
        return self._keyword

    @keyword.setter
    def keyword(self, keyword):
        """Sets the keyword of this Query.

        The keyword used in the inbound message  # noqa: E501

        :param keyword: The keyword of this Query.  # noqa: E501
        :type: str
        """

        self._keyword = keyword

    @property
    def _from(self):
        """Gets the _from of this Query.  # noqa: E501

        The date-time from which you would like matching messages  # noqa: E501

        :return: The _from of this Query.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this Query.

        The date-time from which you would like matching messages  # noqa: E501

        :param _from: The _from of this Query.  # noqa: E501
        :type: str
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this Query.  # noqa: E501

        The date-time to which you would like matching messages  # noqa: E501

        :return: The to of this Query.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this Query.

        The date-time to which you would like matching messages  # noqa: E501

        :param to: The to of this Query.  # noqa: E501
        :type: str
        """

        self._to = to

    @property
    def metadata(self):
        """Gets the metadata of this Query.  # noqa: E501

        An array of objects containing metadata key/value pairs that have been saved on messages.  # noqa: E501

        :return: The metadata of this Query.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this Query.

        An array of objects containing metadata key/value pairs that have been saved on messages.  # noqa: E501

        :param metadata: The metadata of this Query.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Query, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Query):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
