# coding: utf-8

"""
    The SMS Works API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class BatchMessagesApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def cancel_scheduled_batch_job(self, batchid, **kwargs):
        """
        Cancels a scheduled SMS message
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.cancel_scheduled_batch_job(batchid, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str batchid: The ID of the batch you would like returned (required)
        :return: CancelledMessageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.cancel_scheduled_batch_job_with_http_info(batchid, **kwargs)
        else:
            (data) = self.cancel_scheduled_batch_job_with_http_info(batchid, **kwargs)
            return data

    def cancel_scheduled_batch_job_with_http_info(self, batchid, **kwargs):
        """
        Cancels a scheduled SMS message
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.cancel_scheduled_batch_job_with_http_info(batchid, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str batchid: The ID of the batch you would like returned (required)
        :return: CancelledMessageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['batchid']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method cancel_scheduled_batch_job" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'batchid' is set
        if ('batchid' not in params) or (params['batchid'] is None):
            raise ValueError("Missing the required parameter `batchid` when calling `cancel_scheduled_batch_job`")


        collection_formats = {}

        path_params = {}
        if 'batchid' in params:
            path_params['batchid'] = params['batchid']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json;charset=UTF-8'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['JWT']

        return self.api_client.call_api('/batches/schedule/{batchid}', 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='CancelledMessageResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_batch_by_id(self, batchid, **kwargs):
        """
        Retrieve all messages in a batch with the given batch ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_batch_by_id(batchid, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str batchid: The ID of the batch you would like returned (required)
        :return: MessagesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_batch_by_id_with_http_info(batchid, **kwargs)
        else:
            (data) = self.get_batch_by_id_with_http_info(batchid, **kwargs)
            return data

    def get_batch_by_id_with_http_info(self, batchid, **kwargs):
        """
        Retrieve all messages in a batch with the given batch ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_batch_by_id_with_http_info(batchid, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str batchid: The ID of the batch you would like returned (required)
        :return: MessagesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['batchid']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_batch_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'batchid' is set
        if ('batchid' not in params) or (params['batchid'] is None):
            raise ValueError("Missing the required parameter `batchid` when calling `get_batch_by_id`")


        collection_formats = {}

        path_params = {}
        if 'batchid' in params:
            path_params['batchid'] = params['batchid']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json;charset=UTF-8'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['JWT']

        return self.api_client.call_api('/batch/{batchid}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='MessagesResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def schedule_batch(self, sms_message, **kwargs):
        """
        Schedules a batch of SMS messages to be sent at the date-time you specify
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.schedule_batch(sms_message, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param BatchMessage sms_message: Message properties (required)
        :return: ScheduledBatchResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.schedule_batch_with_http_info(sms_message, **kwargs)
        else:
            (data) = self.schedule_batch_with_http_info(sms_message, **kwargs)
            return data

    def schedule_batch_with_http_info(self, sms_message, **kwargs):
        """
        Schedules a batch of SMS messages to be sent at the date-time you specify
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.schedule_batch_with_http_info(sms_message, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param BatchMessage sms_message: Message properties (required)
        :return: ScheduledBatchResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['sms_message']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method schedule_batch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'sms_message' is set
        if ('sms_message' not in params) or (params['sms_message'] is None):
            raise ValueError("Missing the required parameter `sms_message` when calling `schedule_batch`")


        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'sms_message' in params:
            body_params = params['sms_message']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json;charset=UTF-8'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['JWT']

        return self.api_client.call_api('/batch/schedule', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ScheduledBatchResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def send_batch(self, sms_message, **kwargs):
        """
        Send a single SMS message to multiple recipients
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.send_batch(sms_message, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param BatchMessage sms_message: Message properties (required)
        :return: BatchMessageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.send_batch_with_http_info(sms_message, **kwargs)
        else:
            (data) = self.send_batch_with_http_info(sms_message, **kwargs)
            return data

    def send_batch_with_http_info(self, sms_message, **kwargs):
        """
        Send a single SMS message to multiple recipients
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.send_batch_with_http_info(sms_message, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param BatchMessage sms_message: Message properties (required)
        :return: BatchMessageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['sms_message']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method send_batch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'sms_message' is set
        if ('sms_message' not in params) or (params['sms_message'] is None):
            raise ValueError("Missing the required parameter `sms_message` when calling `send_batch`")


        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'sms_message' in params:
            body_params = params['sms_message']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json;charset=UTF-8'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = ['JWT']

        return self.api_client.call_api('/batch/send', 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='BatchMessageResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
